Prefix: "&5&lET &7// "
# How many milliseconds should an action take before the lag is logged to console
Log_Lag_Over_Milis: 100
Locale: en

# allow players to shift click each other to invite to trade
Shift_Click_Trade: true
# is trading money allowed? requires vault and a compatible economy plugin
Economy_Enabled: true
# true -> lock the trading menu from being changed when one party confirms transaction
# false -> only lock the portion of the menu for the party that confirmed
Lock_On_Confirm: false

Debug: [ ]
Version: 0